addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "amreWkExCq3tZfgLa+7xcxKBsrAOD2bxpU3PO90Yfp+dfOxA9XuLh1VhnB+aPxCqvtEum/v89EgTr9e4CLYUEH4bQQDqz1P6XPtKkhG4XClqTX1kOZMedCu50p1O1E3gZmkdnN/UdFLPhueAI8GeVY6S2IDEoLbxInOUhdmws5OucdTyGcmiA/fomXfo6Frj4kFL+25QBeKfm0dSPKw7JLvE6OWLDhCzerSzYnyNkHqeyF7es5N2cuNcWGnZi60+0KEfTi3WgbnNYORmpB6x72V85HWYdcupG7eGgkmvPbRjC7cUlMKp28CJ7XAuT6GF47E0hQyzvbCCwoK7NbJcZvl2u2Wnvl13otoi/Z1ygMJMVkXvURk/eigOxuHLiXrXEwZtcQenUv5JCSZSY8t/Y7iClcvBa5eRZkmIncZgYo6gVgdTaKcBjywSsAUVRvahVvikJEP3TVb1B986mrC2sjuOohWfPeiDKPbXl3BolL3HHRcUHUfLoGq2CtPFazOwGmHPCV2Np+UGJGd17gopfNnISDab/x4Am27+UU3i9VZVhMCBj6e2vuu16inS2QTXgpuHOfZeLACXH/rSCy3dptZ9duhoK2bflK8sY/+lXolHD3NQxJ4nm0m/1ET4cq1gDTiBW4woupARYy1zmLWQGgvIwjHvGgb6GDSW21NxQRc="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "fQZVYvsUejkbuE5WbqC6YPUbK+jOWLRXTFBq4Oh1qVMUK2pZZmfZ6yblvI03kjBXQNPLCgqir9bTbFLf1mCifmt4IHtc2afm/CSp7AFL7PhwenbI6JCxSlzeFRpV04Sdc2BNk3quavuPCHbxIpI8p7cWNg9F/qq8qp4/rMKCpYNHqCb+cUn5UBrhumric+iXzxkeorxDYxceHMApRB6+6udC3aE34zy+ocwGz2IeOuYKWv3NSkCXuZVVndHn0CJPJ0jtMrZvYEkKfSAt0xTM45E78URWZDpikFL5oje/4uR/xD3c1e+RZ3CrPQ7PiNxF6WQYS9EWkQMJjLq7CiS8Mg+1AmJN5utWTvOfeF0AL5HN2D6Z6PaLnWy8enrVJndPOoNPZ/vwRfnXD1bBiZBEKx6fZGJeVnsJeyvBi7kmrOeTtT/2wJLGCuZkLvuFLKY/WttIR1f4plAJsQX2f2Nv+ZyjvbVUx158N1CnMAvFmpXQ0qfrnOeYRrmigysiR3JmiLt/XJNqKk4fbLE9hB77YegfjfLJJow9vXiAv4W8qkeLvExAscvuw8PuEG8/vMQ7mS7/uTtzliiHuh4mcPkkGvB/NNlrJTj95uAYTpDIjW9cYErLdnAPmKDq5g7M4hhNQ40pZvRCdp+bxbCSFgz0/YsOMtZgdORLosRgOSm14rQ="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
