addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "iZkAnAFlswY5TjTvW6lnjSUxh428h8b2WUjWhMNIQUDESm1YGJcBu/XpQb3mv8Mz6ZIYHyoaOcGJCDXF3PN/yRjUSVlTmD1+hVhGfY9yyIDGKAYlWqpN9TOhe5DmoAmTAWGOgBKTdOmmK4QosQSTGfdPcL+c0WgMLKp+yJd+THAwYSH2zJ1k8kfwi/9IB7/pZksRCF1pIolfxx5fn1w8gWzgG9EOyUXTmVo5zaD4+sj7tggHXWnLRmLYP/a5iagpVQ9afJMno2pj1dLNZkTj54OSQrDb2QWfA6MdmuzrGDJT1dUSWQ7q3lsk29MfzTaWIV6HYblsHU2PdOe5PyCH5VuYTdOfwAeIQ5Ty/HPtbE2QkGLGyqKTDqLmX1T2cvcGxI0kJ5NvzlGNKvm2aQBviGeJ36p1iZzLZ3A1UyOIohH8fr7KKIG+tDy6UKFncY0hVkPDb7hGAeN59CpuBJsdwoO7wFYUZ2ohxB7YPyASKTFCgmS6o/mL8FwQ4ZAZPbaulLWsX3NgPjVP7Fdm+1s1zjqTWYbAvJ5Hsl0PnK8vrRJbq/6dqxdEqmMwBwGhOVjQ3m4RkDfwdUda6FXiMSTji2ywPFTFvGC245yKUSbHY7IJwLjwqjIMi1E11oP0+zpD5SnKnRcmRajMlDT+fiziJkgzFtZKJHVMQuZ0a2QLPi8="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "nVP3iEi0gSTkxCGs8DVr2ffF0LqvLJdDfZREArm4U1q14cuQcAiQaqRyk8oe8ZwckPZyvOTH3lTUCCkRho9pxkb0t/EcuR2H9RNtt0inTJspzZpf+P+is1PQlvZGLOy9tkWg8NebbwbyhKQ643Q525L87FThlKAwriCI28OM1D/RKSdsF9sjR1liM9Z8xinUG/QYqhQM+0HGkygq2FbtVRt0CbW77ZFt8Yhi6h7dLxoFB9Y56qog2Yjyy88fqxjQZfDVw9dL//BWHT8opMTNlbMYlIkcslbPwaNdG0nX79wjM3tD+TIks6O292I2l5X4w7SOzbp0WrNhKmBFz2OURkpQ5WEQHxMcYRndXuyBmj4JCVKd6+g1w92+Q8V/RX2z1G2Osqr/VPgIfnjr9LScA89+Tr28c+en6ibvQj2vylk7DDAOTtGkU0upEubTFyzcTLbUq+Cpq7irySYUjMaQ6xpaRzUySd2VlJ0DkBuw3f1BrXQQfDMPVvUKTlKKXcGLCW3eW9ojHzdaXilh1D7dYFfJaIHXasFjHKx11Y2hgyp2uY4HklIZz3w7r4WOOmS6+nLhgfGlN0Tu1gg/Vt6TXlMGJlJ5MAbDUOiR1LdTi2QVAQYMU1vW9TjCe+7zolghQrThgmJnPjlMfUrnD9DjiESf+wpweGVan70TTyc1/PU="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
