language: python
python:
- "3.6"
services: docker
env:
  global:
  # DOCKER_PASS
  - secure: "MYqoK/u9eYftQQK8jWRO2GJSnHN6E0imRtg2f5JYp2PTGfEp64b2bI0ISe0BoanZdylgoysqkdOOxWWETAAV9IO4OHgP+LhARvWhDoVRXmy04IXM7Ha5R07rmvT5jLdJJuPQyXu4Y8nEWKjsZrNwhOnR4/NEuIdazxP9ZsjFGuFrb1xvip9H5LEF/8oN14wUvb1+WQ+OBZay51NTk7Amu4Q19mnpNIPMCcusxJNMwo1r86Z6o+OkBD53t9TELusRytuehbb58vN5/ULArmQ2nrtyo0UqwBhtw7EtGAr+EIpPjCjhLVqgJLyaAM583eJkGooPeHAjk4OFz75cpsnJwK5oL7EmOLq0C3trqHX3HFe8oKWnwxVhOe+1NP3AQijmA1EdgCAS9yGhRg7hRR7LtRB50aGdwJyIBLUF34APCu0YU7ED6NKjsnI8FIzMLu6QvDcT4cGypPJmq7u6HLHu8UAs/8/KF0QOep/AK99b8jOmhWpMSzMkp3Dg3uHPlGh0N4X9UFvgdY2goEhVcP2W5FygOpDXgq7yd7jtJglBnhlXgnpWk+LiWVW4+l7l/bMEhFzNG7WivKAFpZ9VRrk917owdvDd5UJG+NiHd2/1Xcg+eieEXqx5scxElOSzM8lmS+Rn+0g/FI3tHJhCBvwh8TnTxGenKr4ognLqXo+gVS4="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "i8BOHUy5eagSHyohHYjRmSh5dpBw/9t9vBeS1VMBWJpBbiSrFZtlkdzbXpB+YacG+1a+qz+0/Qei8wDwH/YSMnZgi1vWZa46X0N6J9s1FiHJGqCrP49JYSK5heVapqYUZ6HxQGjJ7CRmGVNCc+4EqpA6il2rjqX5EbrOQH1SZalUzyMs0lRqT8GcESiFm1hnozbwCOteGsWC3ngFWwuEoXPBAnFZQ5hSUBHAVYQihw3ny0Zd7219oeN8c0fWhTdpXkrHgCU8UZ+yPIXVpds86LvzujKJlvx79AP0f6D7E1xzYi8zs4zRyPInWZly1BEewu3K0scYi0TLIQYYzkFSRGZzqF4b7heKTlLwg7r3C4oY+BGPr7AB6oD+Y7xG86QpTjkvpsxe10kymPjENMkm3/2NOTpLeF62D5ahX9kEhRtYrsOZgdj/YqRCYdcJz8ZbrdGzntU0xyvKF8CBsLpq5cEoGo9L4Sk0/WGbvlD9viPlcbN7oRbXL2eGBfFJZp5aGviZqgobRHyq90sbUaULGFjPwxnNbI3j2R5FwyX3+Tu4IMGaq7/XdPOedh0dZ9CqwTdRMOYxmIJ0hkocDr9mKczlH7nBH11ak4hDNFS9lc+EIMQc7MVHmVKOF7A0bRHEtLMfpTn23qboveLsxc2gwwCyrp9ViMCKL+kan6C0qjI="
    on_success: always
    on_failure: always

before_install: pip install --upgrade docker-compose invoke pyyaml

install: inv dc.build
script: inv test

after_success:
- inv ci.tag-build
- inv hub.push
- inv hub.update-readme
