version: '2.2'
services:
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    build:
      context: images/couchdb/
      args:
        COUCHDB_VERSION: 2.1.0
    image: ${DOCKER_ORG:-telephoneorg}/couchdb:${DOCKER_TAG:-latest}
    environment:
      COUCHDB_DEV_INIT: 'true'
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      ERLANG_COOKIE: test-cookie
    ports:
    - "5984:5984"
    - "5986:5986"
    networks:
      local:
        aliases:
        - couchdb.local
networks:
  local:
