apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app: couchdb
    project: telephoneorg
    environment: production
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  clusterIP: None
  selector:
    app: couchdb
    project: telephoneorg
    environment: production
  ports:
  - name: data
    port: 5984
  - name: admin
    port: 5986
